name: Run Tests

on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.0'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
  job-connect: 
    needs: run-tests
    runs-on: ubuntu-20.04
    steps: 
      - name: connect to digital ocean
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            if [ ! -d "/home/Winc_CD_repo.git" ]; then
              rm -rf /home/Winc_CD_repo # Remove any existing directory
              git clone https://github.com/Rhomekso/Winc-Assignment-CD.git /home/Winc_CD_repo
            else
              cd /home/Winc_CD_repo
              git pull
            fi
            systemctl restart flask-site
            systemctl status flask-site
